import React from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import moment from "moment";
import { SessionDetail } from "../medical-agent/[sessionId]/page";

type Props = {
  record: SessionDetail;
};

function ViewReportDialog({ record }: Props) {
  const report = record.report;

  // 🔒 HARD NORMALIZATION (prevents all map() crashes)
  const symptoms: string[] = Array.isArray(report?.symptoms)
    ? report.symptoms
    : [];

  const medications: string[] = Array.isArray(report?.medicationsMentioned)
    ? report.medicationsMentioned
    : [];

  const recommendations: string[] = Array.isArray(report?.recommendations)
    ? report.recommendations
    : [];

  if (!report) return null;

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="link" size="sm">
          View Report
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-center text-2xl font-bold text-blue-600">
            Medical AI Voice Agent Report
          </DialogTitle>
        </DialogHeader>

        {/* Session Info */}
        <Section title="Session Info">
          <TwoCol
            left={`Doctor: ${record.selectedDoctor?.specialist}`}
            right={`User: ${report.user || "Anonymous"}`}
          />
          <TwoCol
            left={`Consulted On: ${moment(record.createdOn).format(
              "MMMM Do YYYY, h:mm a"
            )}`}
            right={`Agent: ${report.agent}`}
          />
        </Section>

        {/* Chief Complaint */}
        <Section title="Chief Complaint">
          <p>{report.chiefComplaint || "Not specified."}</p>
        </Section>

        {/* Summary */}
        <Section title="Summary">
          <p>{report.summary}</p>
        </Section>

        {/* Symptoms */}
        <Section title="Symptoms">
          {symptoms.length > 0 ? (
            <ul className="list-disc pl-5">
              {symptoms.map((s, i) => (
                <li key={i}>{s}</li>
              ))}
            </ul>
          ) : (
            <p>No symptoms recorded.</p>
          )}
        </Section>

        {/* Duration & Severity */}
        <Section title="Duration & Severity">
          <TwoCol
            left={`Duration: ${report.duration || "N/A"}`}
            right={`Severity: ${report.severity || "N/A"}`}
          />
        </Section>

        {/* Medications */}
        <Section title="Medications Mentioned">
          {medications.length > 0 ? (
            <ul className="list-disc pl-5">
              {medications.map((med, i) => (
                <li key={i}>{med}</li>
              ))}
            </ul>
          ) : (
            <p>No medications mentioned.</p>
          )}
        </Section>

        {/* Recommendations */}
        <Section title="Recommendations">
          {recommendations.length > 0 ? (
            <ul className="list-disc pl-5">
              {recommendations.map((rec, i) => (
                <li key={i}>{rec}</li>
              ))}
            </ul>
          ) : (
            <p>No recommendations provided.</p>
          )}
        </Section>

        {/* Footer Disclaimer */}
        <p className="mt-4 text-xs text-center text-gray-400">
          This report was generated by an AI Medical Assistant for informational
          purposes only.
        </p>
      </DialogContent>
    </Dialog>
  );
}

export default ViewReportDialog;

/* ----------------- Helpers ----------------- */

const Section = ({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) => (
  <div className="mt-6">
    <h3 className="font-bold text-blue-500 border-b pb-1 mb-2">
      {title}
    </h3>
    <div className="text-sm text-gray-700">{children}</div>
  </div>
);

const TwoCol = ({ left, right }: { left: string; right: string }) => (
  <div className="grid grid-cols-2 gap-4 text-sm">
    <p>{left}</p>
    <p>{right}</p>
  </div>
);
